.github/workflows/gke-dev.yml, .github/workflows/gke-prod.yml
=> chore: update image

.github/workflows/ci-test.yml, dbconfig.yml, pkg/config/config.go
=> chore: update test config

.github/workflows/ci-test.yml, .github/workflows/gke-dev.yml, .github/workflows/gke-prod.yml
=> chore: update config

dbconfig.yml
=> chore: add test config

CODEOWNERS
=> feat: add github default code reviewer

docs/docs.go, docs/swagger.json, docs/swagger.yaml, migrations/seed/seed.sql, migrations/test_seed/seed.sql, pkg/handler/metadata/interface.go, pkg/handler/metadata/metadata.go, pkg/handler/metadata/metadata_test.go, pkg/handler/metadata/testdata/get_account_roles/200.json, pkg/model/roles.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/role/interface.go, pkg/store/role/role.go, pkg/store/store.go, pkg/view/metadata.go
What's this PR do?
create api to get list values for account roles
Screenshots (if appropriate)
```
curl 'http://localhost:8200/api/v1/metadata/account-roles'
-H 'accept: /'
--compressed
```
```
{
"data": [
{
"id": "11ccffea-2cc9-4e98-9bef-3464dfe4dec8",
"createdAt": …
```
=> feat: api get list account roles

docs/docs.go, docs/swagger.json, docs/swagger.yaml, migrations/schemas/20221107212507-add_senitorities_in_employees_table.sql, migrations/seed/seed.sql, migrations/test_seed/seed.sql, pkg/handler/metadata/interface.go, pkg/handler/metadata/metadata.go, pkg/handler/metadata/metadata_test.go, pkg/handler/metadata/testdata/get_seniorities/200.json, pkg/model/senitorities.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/position/position.go, pkg/store/seniority/interface.go, pkg/store/seniority/senitority.go, pkg/store/store.go, pkg/view/metadata.go
What's this PR do?
create api to get list values for seniorities
Screenshots (if appropriate)
```
curl 'http://localhost:8200/api/v1/metadata/seniorities'
-H 'accept: /'
--compressed
```
```
{
"data": [{
"id": "11ccffea-2cc9-4e98-9bef-3464dfe4dec8",
"created_at": …
```
=> feat: api get list seniorities

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/metadata/interface.go, pkg/handler/metadata/metadata.go, pkg/handler/metadata/metadata_test.go, pkg/handler/metadata/testdata/get_project_statuses/200.json, pkg/routes/v1.go, pkg/routes/v1_test.go
https://www.notion.so/dwarves/API-GET-project-status-11e4fecaa0d14aa59d158eb4e877e9b6
```
curl 'http://localhost:8200/api/v1/metadata/project-statuses'
-H 'accept: /'
--compressed
```
```
{
"data": [
{
"code": "on-boarding",
"name": "On Boarding"
},
{
"code": "paused",
"name": …
```
=> feat: api get project statuses

migrations/schemas/20221114112859-create_employee_positions_table.sql, pkg/model/employee_positions.go
=> chore: create employee position table

docs/docs.go, docs/swagger.json, docs/swagger.yaml, go.mod, go.sum, migrations/test_seed/seed.sql, pkg/handler/project/interface.go, pkg/handler/project/project.go, pkg/handler/project/project_test.go, pkg/handler/project/request.go, pkg/handler/project/testdata/update_project_status/200.json, pkg/handler/project/testdata/update_project_status/400.json, pkg/handler/project/testdata/update_project_status/500.json, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/project/interface.go, pkg/store/project/project.go, pkg/view/project.go
https://www.notion.so/API-to-update-project-status-f98e5f7851614e03aaae5d2e073c95c2
```
curl 'http://localhost:8200/api/v1/projects/8dc3be2e-19a4-4942-8a79-56db391a0b15/status'
-H 'accept: /'
-H 'authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTkzMjExNDIsImlkIj …
```
=> Feat: update project status

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/employee/employee.go
=> fix: remove working status required

dbconfig.yml
=> chore: migrate db

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/employee/employee.go, pkg/handler/project/project.go
=> fix: add missing authorization header in swagger

docs/docs.go, docs/swagger.json, docs/swagger.yaml, migrations/test_seed/seed.sql, pkg/handler/employee/employee.go, pkg/handler/employee/employee_test.go, pkg/handler/employee/interface.go, pkg/handler/employee/request.go, pkg/handler/employee/testdata/update_general_info/200.json, pkg/handler/employee/testdata/update_general_info/404.json, pkg/handler/employee/testdata/update_general_info/500.json, pkg/handler/employee/testdata/update_personal_info/200.json, pkg/handler/employee/testdata/update_personal_info/404.json, pkg/handler/employee/testdata/update_skills/200.json, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/employee/employee.go, pkg/store/employee/interface.go, pkg/store/employee/request.go, pkg/view/employee.go
https://www.notion.so/dwarves/API-to-edit-employee-info-62f923ea04a843ad96794cd1d0d3cb50
```
curl 'http://localhost:8200/api/v1/employees/2655832e-f009-4b73-a535-64c3a22e558f/personal-info'
-X PUT
-H 'accept: /'
-H 'authorization:Bearer …
```
=> feat: api update personal info

pkg/model/base.go
- We are using both of gorm v1 and v2. So I update it to v2 for consistency.
=> chore: update gorm v2 in base model

docs/docs.go, docs/swagger.json, docs/swagger.yaml, go.mod, go.sum, pkg/handler/employee/employee.go, pkg/handler/employee/errors.go, pkg/handler/employee/request.go, pkg/model/positions.go, pkg/model/stacks.go, pkg/store/chapter/chapter.go, pkg/store/chapter/interface.go, pkg/store/employee/employee.go, pkg/store/employee/interface.go, pkg/store/employee/request.go, pkg/store/employeeposition/employeepositon.go, pkg/store/employeeposition/interface.go, pkg/store/employeestack/employeestack.go, pkg/store/employeestack/interface.go, pkg/store/seniority/interface.go, pkg/store/seniority/seniority.go, pkg/store/store.go
=> chore: update transaction for api edit skills

Makefile
=> chore: update test

docs/docs.go, docs/swagger.json, docs/swagger.yaml, migrations/schemas/20221117123000-alter_working_status_type.sql, pkg/handler/employee/employee.go, pkg/handler/employee/employee_test.go, pkg/handler/employee/request.go, pkg/handler/employee/testdata/create/invalid_uuid.json, pkg/handler/employee/testdata/create/validation_err.json, pkg/handler/metadata/metadata.go, pkg/model/employees.go, pkg/model/positions.go
=> chore: update swagger for creating new employee

migrations/schemas/20221117123000-alter_working_status_type.sql
=> fix: migrate add value

pkg/handler/employee/testdata/list/have_working_and_no_pagination.json, pkg/handler/employee/testdata/list/have_working_and_pagination.json, pkg/handler/employee/testdata/list/without_working_status_and_pagination.json, pkg/store/employee/employee.go, pkg/view/employee.go, pkg/view/position.go, pkg/view/project.go
=> chore: update employee detail api

docs/docs.go, docs/swagger.json, docs/swagger.yaml
=> chore: update swagger for employee detail

pkg/handler/auth/auth.go, pkg/handler/employee/employee.go, pkg/handler/employee/testdata/list/have_working_and_no_pagination.json, pkg/handler/employee/testdata/list/have_working_and_pagination.json, pkg/handler/employee/testdata/list/without_working_status_and_pagination.json, pkg/handler/metadata/metadata.go, pkg/handler/profile/profile.go, pkg/handler/project/project.go, pkg/store/employee/employee.go, pkg/view/employee.go, pkg/view/position.go, pkg/view/project.go, pkg/view/response.go
Because our resp has no support for the only message. So I added the message resp in the CreateResponse Function
=> chore: implement general msg resp

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/employee/employee.go, pkg/handler/employee/employee_test.go, pkg/handler/employee/request.go, pkg/handler/employee/testdata/list/with_preload_false.json, pkg/handler/employee/testdata/list/without_preload.json, pkg/model/employees.go, pkg/store/employee/employee.go, pkg/store/employee/request.go, pkg/view/employee.go
https://www.notion.so/dwarves/API-to-GET-employee-list-For-selection-box-f13e313855784c78b8357891a093e033
```
curl --location --request GET 'http://localhost:8200/api/v1/employees?workingStatus=probation&preload=false' \
--data-raw ''
--data-raw ''
```
```
{
"page": 0,
"size": 50,
"sort": "",
"total": 1,
"data": [
{
"id": "ecea9d15-05ba-4a4e-9787-54210e3b98ce", …
```
=> feat: get employee for selection box

pkg/handler/employee/employee.go, pkg/handler/employee/employee_test.go, pkg/store/employee/employee.go, pkg/store/employee/interface.go
=> fix: error when update employee status

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/employee/employee.go, pkg/handler/employee/testdata/list/have_working_and_no_pagination.json, pkg/handler/employee/testdata/list/with_preload_false.json, pkg/handler/employee/testdata/list/without_preload.json, pkg/handler/employee/testdata/list/without_working_status_and_pagination.json, pkg/handler/project/testdata/get_members/200.json, pkg/model/pagination.go
=> chore: update pagination

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/profile/profile.go, pkg/handler/profile/profile_test.go, pkg/handler/profile/request.go, pkg/handler/profile/testdata/get_profile/200.json, pkg/store/employee/employee.go, pkg/store/employee/request.go, pkg/view/profile.go
=> chore: add personal email in update profile api

migrations/test_seed/seed.sql, pkg/handler/project/interface.go, pkg/handler/project/project.go, pkg/handler/project/project_test.go, pkg/handler/project/testdata/get_project/200.json, pkg/handler/project/testdata/get_project/404.json, pkg/model/projects.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/project/interface.go, pkg/store/project/project.go, pkg/view/employee.go, pkg/view/project.go, pkg/view/stack.go
=> feat: get project detail

docs/docs.go, docs/swagger.json, docs/swagger.yaml
=> feat: gen get project detail swagger

docs/docs.go, docs/swagger.json, docs/swagger.yaml, migrations/schemas/20221122131610-alter_project_table.sql, pkg/handler/project/errors.go, pkg/handler/project/interface.go, pkg/handler/project/project.go, pkg/handler/project/project_test.go, pkg/handler/project/request.go, pkg/handler/project/testdata/create/200.json, pkg/handler/project/testdata/get_project/200.json, pkg/handler/project/testdata/update_general_info/200.json, pkg/handler/project/testdata/update_general_info/404.json, pkg/model/projects.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/country/country.go, pkg/store/country/interface.go, pkg/store/project/filter.go, pkg/store/project/interface.go, pkg/store/project/project.go, pkg/store/projectstack/interface.go, pkg/store/projectstack/projectstack.go, pkg/store/store.go, pkg/view/project.go
```
curl --location --request PUT 'http://localhost:8200/api/v1/projects/8dc3be2e-19a4-4942-8a79-56db391a0b15/general-info' \
--header 'Content-Type: application/json' \
--data-raw '{
"name":"Fortress",
"startDate":"1990-01-02T00:00:00+08:00",
"countryID":"4ef64490-c906-4192-a7f9-d2221dadfe4c",
"stacks":[
"fa0f4e46-7eab-4e5c-9d31-30489e69fe2e", …
```
=> feat: update project general info api

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/project/testdata/get_members/200.json, pkg/handler/project/testdata/get_project/200.json, pkg/view/project.go
=> chore: update get members api

pkg/model/employees.go, pkg/store/project/project.go
=> feat: remove account status code

pkg/service/vault/vault.go
=> fix: vault get bool value

pkg/handler/project/testdata/get_members/200.json, pkg/store/projectslot/project_slot.go, pkg/view/project.go
=> fix: position when get project members

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/employee/employee.go, pkg/handler/employee/employee_test.go, pkg/handler/employee/errors.go, pkg/handler/employee/request.go, pkg/handler/employee/testdata/update_employee_status/200.json, pkg/handler/project/testdata/get_members/200.json, pkg/handler/project/testdata/get_project/200.json, pkg/view/project.go
=> chore: update get project members response

docs/docs.go, docs/swagger.json, docs/swagger.yaml, migrations/schemas/20221123084531-drop_contraint_in_project_heads_table.sql, migrations/test_seed/seed.sql, pkg/handler/employee/employee.go, pkg/handler/project/errors.go, pkg/handler/project/interface.go, pkg/handler/project/project.go, pkg/handler/project/project_test.go, pkg/handler/project/request.go, pkg/handler/project/testdata/get_project/200.json, pkg/handler/project/testdata/update_contact_info/200.json, pkg/handler/project/testdata/update_contact_info/404.json, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/project/filter.go, pkg/store/project/interface.go, pkg/store/project/project.go, pkg/store/projecthead/interface.go, pkg/store/projecthead/project.go, pkg/store/projectslot/project_slot.go, pkg/view/project.go
```
curl --location --request PUT 'http://localhost:8200/api/v1/projects/8dc3be2e-19a4-4942-8a79-56db391a0b15/contact-info' \
--header 'Content-Type: application/json' \
--data-raw '{
"clientEmail":"fortress@gmai.com",
"projectEmail":"fortress@d.foundation",
"accountManagerID":"2655832e-f009-4b73-a535-64c3a22e558f",
"deliveryManagerID": …
```
=> feat: update project contact info api

migrations/seed/seed.sql, pkg/handler/employee/employee.go, pkg/model/employee_roles.go, pkg/store/employeerole/employee_role.go, pkg/store/employeerole/interface.go, pkg/store/store.go
=> fix: creating employee lead to create metadata

go.mod, go.sum, pkg/config/config.go, pkg/service/notion/interface.go, pkg/service/notion/notion.go, pkg/service/service.go, pkg/service/vault/vault.go
=> feat: init notion service

Makefile, pkg/config/config.go, pkg/service/google/google.go, pkg/service/service.go, pkg/service/vault/vault.go
=> fix: gcs credentials

pkg/handler/profile/profile.go
=> fix: avatar path

docs/docs.go, docs/swagger.json, docs/swagger.yaml, go.mod, go.sum, migrations/test_seed/seed.sql, pkg/handler/project/project.go, pkg/handler/project/project_test.go, pkg/handler/project/request.go, pkg/handler/project/testdata/get_list_work_unit/200.json, pkg/handler/project/testdata/get_list_work_unit/400.json, pkg/handler/project/testdata/get_list_work_unit/404.json, pkg/model/work_units.go, pkg/store/workunit/interface.go, pkg/store/workunit/work_unit.go, pkg/view/work_unit.go
https://www.notion.so/dwarves/API-to-get-the-list-of-work-unitsa-6c991a98ed76407ca32f11bdef0e0296
```
- Validator input params
- Check project existence
- Get all work unit by project id
```
```
curl --location --request GET 'http://localhost:8200/api/v1/projects/8dc3be2e-19a4-4942-8a79-56db391a0b15/work-units?status=active' \
--data-raw ''
```
```
{
"data": [
{
"id": …
```
=> feat: get list work unit api

migrations/schemas/20221205153244-create_tables_for_feedback.sql, migrations/seed/seed.sql, migrations/test_seed/seed.sql, pkg/model/answer.go, pkg/model/answer_drafts.go, pkg/model/employee_even_reviewer.go, pkg/model/employee_even_topics.go, pkg/model/employee_event_questions.go, pkg/model/feedback_events.go, pkg/model/questions.go
=> feat: models for feedback tables

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/project/project.go, pkg/handler/project/request.go, pkg/store/workunit/work_unit.go
=> fix: get members for archived project

docs/docs.go, docs/swagger.json, docs/swagger.yaml, migrations/schemas/20221208010306-alter_employee_event_question_table.sql, migrations/seed/seed.sql, migrations/test_seed/seed.sql, pkg/handler/feedback/errors.go, pkg/handler/feedback/feedback.go, pkg/handler/feedback/feedback_test.go, pkg/handler/feedback/interface.go, pkg/handler/feedback/request.go, pkg/handler/feedback/testdata/detail/200.json, pkg/handler/feedback/testdata/detail/404.json, pkg/model/employee_event_reviewer.go, pkg/model/questions.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/employeeeventquestion/employee_event_question.go, pkg/store/employeeeventquestion/interface.go, pkg/store/employeeeventreviewer/employee_event_reviewer.go, pkg/store/employeeeventreviewer/interface.go, pkg/store/employeeeventtopic/employee_event_topic.go, pkg/store/employeeeventtopic/interface.go, pkg/store/store.go, pkg/view/feedback.go
https://www.notion.so/dwarves/API-to-get-feedback-topic-details-for-logged-in-user-0505ef91dfdb4d48bdadf137075ae7fd
```
curl --location --request GET 'http://localhost:8200/api/v1/feedbacks/8a5bfedb-6e11-4f5c-82d9-2635cfcce3e2/topics/e4a33adc-2495-43cf-b816-32feb8d5250d' \
--data-raw ''
```
```
{
"data": {
"answers": [
{
"eventQuestionID": …
```
=> feat: get feedback detail api

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/feedback/errs/errors.go, pkg/handler/feedback/feedback.go, pkg/handler/feedback/interface.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/employeeeventquestion/employee_event_question.go, pkg/store/employeeeventquestion/interface.go, pkg/store/employeeeventreviewer/employee_event_reviewer.go, pkg/store/employeeeventreviewer/interface.go, pkg/store/employeeeventtopic/employee_event_topic.go, pkg/store/employeeeventtopic/interface.go
curl
```
curl --location --request DELETE 'http://localhost:8200/api/v1/surveys/8a5bfedb-6e11-4f5c-82d9-2635cfcce3e2/topics/e4a33adc-2495-43cf-b816-32feb8d5250d'
```
response:
```
{
"data": null,
"message": "ok"
}
```
ticket: https://www.notion.so/dwarves/4d756d46e90240918cd2505f962cacd1?v=d65335d1772f4532ab1bc274a1ae8c76&p=24dcbb401c394b3a8f1016ec74d9f03d&pm=s
=> feat: add delete survey topic api

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/feedback/feedback.go, pkg/handler/feedback/feedback_test.go, pkg/handler/feedback/interface.go, pkg/handler/feedback/request/request.go, pkg/handler/feedback/testdata/get_peer_review_detail/200.json, pkg/handler/feedback/testdata/get_peer_review_detail/404.json, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/employeeeventtopic/employee_event_topic.go, pkg/view/feedback.go
https://www.notion.so/API-to-get-peer-review-event-details-Admin-dca172ccf23b4749a1d74aa0518df228
```
curl --location --request GET 'http://localhost:8200/api/v1/surveys/8a5bfedb-6e11-4f5c-82d9-2635cfcce3e2' \
--data-raw ''
```
```
{
"data": {
"topicID": "e4a33adc-2495-43cf-b816-32feb8d5250d",
"title": "Review Thuong Phung",
"employee": {
"id": …
```
=> feat: get peer review detail

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/survey/request/request.go, pkg/handler/survey/survey.go, pkg/handler/survey/survey_test.go
https://www.notion.so/dwarves/Enhance-Sending-Engagement-Survey-API-to-send-survey-for-all-employees-that-we-no-longer-require-the-1d0daf2783824cbf9f49b36f9290aa95
=> chore: send survey without participants list

pkg/handler/employee/employee.go, pkg/handler/feedback/feedback.go, pkg/handler/profile/profile.go, pkg/handler/project/project.go, pkg/handler/survey/survey.go, pkg/store/content/content.go, pkg/store/content/interface.go, pkg/store/employeechapter/employee_chapter.go, pkg/store/employeeeventquestion/employee_event_question.go, pkg/store/employeeeventreviewer/employee_event_reviewer.go, pkg/store/employeeeventreviewer/interface.go, pkg/store/feedbackevent/feedback_event.go, pkg/store/feedbackevent/interface.go, pkg/store/project/interface.go, pkg/store/project/project.go, pkg/store/projectmember/interface.go, pkg/store/projectmember/project_member.go, pkg/store/workunit/interface.go, pkg/store/workunit/work_unit.go, pkg/store/workunitmember/interface.go, pkg/store/workunitmember/work_unit_member.go
https://www.notion.so/dwarves/4d756d46e90240918cd2505f962cacd1?v=d65335d1772f4532ab1bc274a1ae8c76&p=9b2a3aeb184d42219535dfe33524a40d&pm=s
=> chore: standardize function name

pkg/handler/project/project.go, pkg/store/projectmember/project_member.go, pkg/store/projectslot/project_slot.go, pkg/store/workunitmember/work_unit_member.go
https://www.notion.so/dwarves/Should-be-able-to-add-inactive-members-to-a-work-unit-c9a42ebf81a446b79a36749393e5cfdf
=> chore: uncheck inactive status condition

pkg/handler/project/project.go
https://www.notion.so/dwarves/Allow-to-edit-inactive-members-93b79b5841e8446dbf5a025cd9c238d8
=> chore: remove active member check

pkg/store/projectslot/project_slot.go
=> fix: get project members

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/profile/profile.go, pkg/handler/profile/profile_test.go, pkg/handler/profile/request/request.go, pkg/handler/profile/testdata/update_info/200.json
https://www.notion.so/Enhance-API-update-and-get-profile-56ad86c5f3444203a8db4b43bbdb8866
=> chore: enhance update profile api

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/employee/testdata/one/200.json, pkg/handler/employee/testdata/update_employee_status/200.json, pkg/store/employee/employee.go, pkg/view/employee.go
https://www.notion.so/dwarves/4d756d46e90240918cd2505f962cacd1?v=d65335d1772f4532ab1bc274a1ae8c76&p=f9068333ea38412cadaaf72f4d3e5d00&pm=s
=> chore: update employee project response

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/profile/profile.go, pkg/handler/profile/request/request.go
=> Fix/ remove discordID

pkg/handler/employee/employee.go, pkg/utils/auth.go
=> fix: search employees by ApiKey

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/employee/employee.go, pkg/handler/employee/employee_test.go, pkg/handler/employee/request/request.go, pkg/handler/employee/testdata/update_general_info/200.json, pkg/view/employee.go
https://www.notion.so/dwarves/Allow-admin-to-update-an-employee-s-nickname-176fb591b023496085b4c861558389a8
=> chore: add display name in api update general info

migrations/schemas/20230106075550-alter_seniorities_add_level.sql, migrations/seed/metadata.sql, migrations/test_seed/seed.sql, pkg/handler/employee/testdata/one/200.json, pkg/handler/employee/testdata/update_employee_status/200.json, pkg/handler/employee/testdata/update_skills/200.json, pkg/handler/metadata/testdata/get_seniorities/200.json, pkg/handler/project/testdata/assign_member/200_success.json, pkg/handler/project/testdata/get_members/200.json, pkg/handler/project/testdata/get_project/200.json, pkg/handler/project/testdata/update_member/200_success.json, pkg/model/senitorities.go, pkg/store/project/project.go
https://www.notion.so/dwarves/4d756d46e90240918cd2505f962cacd1?v=d65335d1772f4532ab1bc274a1ae8c76&p=7fc0caa594d24c048d35dc7db8a7ee41&pm=s
=> chore: update sorting order members in project

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/employee/employee.go, pkg/handler/employee/request/request.go, pkg/store/employee/request.go, pkg/store/employee/util.go
https://www.notion.so/dwarves/4d756d46e90240918cd2505f962cacd1?v=d65335d1772f4532ab1bc274a1ae8c76&p=312618233a694f2e9505d7d1c4eb5ab9&pm=s
=> chore: add filter by empty to get employees

Makefile, migrations/schemas/20221127165238-create_invoices_table.sql, migrations/schemas/20221212015000-alter_table_add_missing_column.sql, migrations/schemas/20230106033811-accounting.sql, migrations/schemas/20230106033812-valuation.sql, pkg/config/config.go, pkg/handler/handler.go, pkg/handler/valuation/interface.go, pkg/handler/valuation/valuation.go, pkg/model/asset.go, pkg/model/liability.go, pkg/model/valuation.go, pkg/model/wise.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/service/service.go, pkg/service/vault/vault.go, pkg/service/wise/interface.go, pkg/service/wise/wise.go, pkg/store/employeementee/employee_mentee.go, pkg/store/store.go, pkg/store/valuation/interface.go, pkg/store/valuation/valuation.go, pkg/utils/strings.go, pkg/utils/strings_test.go
- add valuation calculation logic
- migrate db with new view
=> feat: valuation calculation

go.mod, go.sum, migrations/schemas/20230109154551-init_audit_schema.sql
=> feat: init audit database

pkg/view/project.go
=> fix: return leftDate

pkg/config/config.go, pkg/cronjob/audit/audit.go, pkg/handler/audience/audience.go, pkg/handler/audience/interface.go, pkg/handler/earn/earn.go, pkg/handler/handler.go, pkg/handler/techradar/tech_radar.go, pkg/model/audience.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/service/notion/interface.go, pkg/service/notion/notion.go
=> feat: add audiences API

go.mod, go.sum, pkg/config/config.go, pkg/handler/auth/auth.go, pkg/handler/employee/employee.go, pkg/handler/feedback/feedback.go, pkg/handler/handler.go, pkg/handler/metadata/metadata.go, pkg/handler/metadata/metadata_test.go, pkg/handler/profile/profile.go, pkg/handler/project/project.go, pkg/handler/survey/survey.go, pkg/model/auth.go, pkg/mw/mw.go, pkg/mw/mw_test.go, pkg/routes/v1.go, pkg/utils/auth.go, pkg/utils/auth_test.go
https://www.notion.so/dwarves/4d756d46e90240918cd2505f962cacd1?v=d65335d1772f4532ab1bc274a1ae8c76&p=106cb5ac78d346859b80d4cca5b603c3&pm=s
=> feat: add jwt secret key

pkg/config/config.go, pkg/handler/event/event.go, pkg/handler/event/interface.go, pkg/handler/handler.go, pkg/handler/hiring/hiring.go, pkg/handler/hiring/interface.go, pkg/model/date_time.go, pkg/model/event.go, pkg/model/hiring_position.go, pkg/routes/v1.go, pkg/routes/v1_test.go
=> feat: add events, hirings API

pkg/handler/hiring/hiring.go
=> fix: filter hiring position by status

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/dashboard/dashboard.go, pkg/handler/dashboard/testdata/audits/200_with_project_id.json, pkg/handler/dashboard/testdata/audits/200_without_project_id.json, pkg/handler/dashboard/testdata/engineering_healths/200_with_project_id.json, pkg/handler/dashboard/testdata/engineering_healths/200_without_project_id.json, pkg/handler/hiring/hiring.go, pkg/view/dashboard.go, pkg/view/hiring.go
=> chore: update health engineering and audit response

pkg/config/config.go, pkg/handler/handler.go, pkg/handler/staffingdemand/interface.go, pkg/handler/staffingdemand/staffing_demand.go, pkg/model/staffing_demand.go, pkg/routes/v1.go, pkg/routes/v1_test.go
=> feat: add staffing demand api

go.mod, go.sum, pkg/config/config.go, pkg/handler/project/interface.go, pkg/handler/project/project.go, pkg/model/project_milestone.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/service/notion/interface.go, pkg/service/notion/notion.go, pkg/service/service.go
=> feat: add get project milestones api

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/cronjob/audit/audit.go, pkg/handler/audit/audit.go, pkg/handler/audit/interface.go, pkg/handler/handler.go, pkg/model/action_item_snapshot.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/store/actionitemsnapshot/action_item_snapshot.go, pkg/store/actionitemsnapshot/interface.go
https://www.notion.so/dwarves/API-for-manual-request-sync-audit-5a83237d0b914067aa0176916bf2c049
```
curl --location --request PUT 'http://localhost:8200/api/v1/audits' \
--data-raw ''
```
```
{
"data": null,
"message": "sync audit from notion successfully"
}
```
=> feat: manually sync audit data from notion

pkg/config/config.go, pkg/service/service.go
=> chore: udpate name for audit notion secret

pkg/cronjob/audit/audit.go, pkg/handler/audience/audience.go, pkg/handler/digest/digest.go, pkg/handler/earn/earn.go, pkg/handler/event/event.go, pkg/handler/hiring/hiring.go, pkg/handler/memo/memo.go, pkg/handler/project/project.go, pkg/handler/staffingdemand/staffing_demand.go, pkg/handler/techradar/tech_radar.go, pkg/handler/update/update.go, pkg/service/notion/interface.go, pkg/service/notion/notion.go
=> chore: add notion pageSize

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/project/project.go, pkg/handler/project/request/request.go, pkg/handler/project/testdata/get_project/200.json, pkg/handler/project/testdata/get_projects/200.json, pkg/handler/project/testdata/update_general_info/200.json, pkg/view/project.go
https://www.notion.so/dwarves/Add-notionID-field-for-project-5ca2751b4aad4046bf9b1806e16770b8
=> chore: add notion id for projects

pkg/handler/techradar/tech_radar.go
=> chore: update notion techradar

migrations/schemas/20230207030447-add_notion_id_for_projects.sql
=> chore: migrate notion id for projects

pkg/config/config.go, pkg/handler/audience/audience.go, pkg/handler/audit/audit.go, pkg/handler/digest/digest.go, pkg/handler/earn/earn.go, pkg/handler/event/event.go, pkg/handler/hiring/hiring.go, pkg/handler/memo/memo.go, pkg/handler/project/project.go, pkg/handler/staffingdemand/staffing_demand.go, pkg/handler/techradar/tech_radar.go, pkg/handler/update/update.go, pkg/service/service.go
=> chore: update notion database

migrations/schemas/20230206045042-alter_employees_table.sql, migrations/schemas/20230207063521-alter_projects_table.sql
=> fix: migrate bank account id for projects

migrations/schemas/20230207030447-add_notion_id_for_projects.sql
=> fix: missing migrate file

migrations/schemas/20230208143342-add_project_notion_table.sql
=> fix: violates foreign key constrain in migration

pkg/handler/audit/audit.go
=> chore: skip unmap project when sync audit data

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/view/dashboard.go
=> fix: swagger for summary work unit distribution

pkg/view/dashboard.go
=> fix: divide by zero case

go.mod, go.sum, pkg/config/config.go, pkg/handler/handler.go, pkg/handler/issue/interface.go, pkg/handler/issue/issue.go, pkg/handler/techradar/tech_radar.go, pkg/model/issue.go, pkg/model/tech_radar.go, pkg/routes/v1.go, pkg/routes/v1_test.go
=> feat: add api get Notion issues

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/project/project.go
=> fix: add swagger for distinct query

pkg/handler/audit/audit.go, pkg/store/dashboard/dashboard.go, pkg/view/dashboard.go
=> fix: not count done action item for snapshot

pkg/handler/techradar/interface.go, pkg/handler/techradar/tech_radar.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/service/notion/interface.go, pkg/service/notion/notion.go
=> feat: add api create tech radar item

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/dashboard/dashboard.go, pkg/handler/dashboard/testdata/action_item_squash/200.json, pkg/handler/dashboard/testdata/action_item_squash/200_with_project_id.json, pkg/handler/dashboard/testdata/project_sizes/200.json, pkg/model/dashboard.go, pkg/store/dashboard/dashboard.go, pkg/view/dashboard.go
=> fix: show nonaudit project in summary dashboard

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/handler/survey/request/request.go, pkg/handler/survey/survey.go, pkg/store/employeeeventtopic/employee_event_topic.go, pkg/store/employeeeventtopic/request.go
=> fix: survey detail query

pkg/handler/project/project.go, pkg/handler/project/project_test.go, pkg/handler/project/request/request.go
=> fix: commission rate type

pkg/handler/df_update/df_update.go
=> feat: add preview to send df updates

migrations/schemas/20230307184910-create_payroll_tables.sql
=> fix: add cached_payrolls table

pkg/handler/payroll/payroll.go, pkg/store/employee/request.go, pkg/store/employee/util.go
=> fix: fix query to filter employees by batch date

migrations/schemas/20230307184910-create_payroll_tables.sql
=> refactor(migrations): change data type of basecamp_id column 

pkg/handler/payroll/payroll.go
=> chore: add TWRecipientName field to payrollResponse struct

pkg/handler/dashboard/testdata/get_resource_utilization/200_ok.json, pkg/service/discord/discord.go, pkg/service/discord/service.go
https://user-images.githubusercontent.com/81815108/229753256-26baae89-a42d-4622-8ac1-c5b8b0d66ccc.mov
=> feat: add send message functionality for discord service

pkg/handler/birthday/birthday.go, pkg/service/basecamp/consts/consts.go
=> feat: create basecamp todo on basecamp for birthday

pkg/handler/notion/project_milestone.go, pkg/model/notion.go
=> chore: update project milestones db

migrations/schemas/20230512091353-drop-old-icy-txn.sql, migrations/schemas/20230512091526-new-icy-txn.sql, migrations/schemas/20230512110852-report-views.sql
https://earn.d.foundation/Database-view-to-show-team-stats-3d38712d0b654e089028a805741f17ca
=> feat: add migration for icy txn and reports views

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/controller/employee/list.go, pkg/controller/employee/update_general_info.go, pkg/handler/employee/employee.go, pkg/handler/employee/employee_test.go, pkg/handler/employee/errs/errors.go, pkg/handler/employee/request/request.go, pkg/handler/employee/testdata/create/validation_err.json, pkg/handler/employee/testdata/one/200.json, pkg/handler/employee/testdata/update_employee_status/200.json, pkg/handler/employee/testdata/update_skills/200.json, pkg/view/auth_test.go, pkg/view/chapter.go, pkg/view/currency.go, pkg/view/employee.go, pkg/view/pagination.go, pkg/view/uuid.go, pkg/view/uuid_test.go
=> chore: update employee swagger document

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/controller/employee/list.go, pkg/controller/employee/update_general_info.go, pkg/handler/dashboard/dashboard.go, pkg/handler/employee/employee.go, pkg/handler/employee/employee_test.go, pkg/handler/employee/errs/errors.go, pkg/handler/employee/request/request.go, pkg/handler/employee/testdata/create/validation_err.json, pkg/handler/employee/testdata/one/200.json, pkg/handler/employee/testdata/update_employee_status/200.json, pkg/handler/employee/testdata/update_skills/200.json, pkg/view/auth_test.go, pkg/view/chapter.go, pkg/view/currency.go, pkg/view/dashboard.go, pkg/view/employee.go, pkg/view/pagination.go, pkg/view/project.go, pkg/view/uuid.go, pkg/view/uuid_test.go
=> chore: update dashboard swagger document

go.mod, go.sum, pkg/handler/accounting/accounting.go
=> fix: correct hado description, amount format

pkg/handler/accounting/accounting.go
=> feat: add accounting.out cbre monthly

.github/workflows/golangci-lint.yaml, pkg/handler/discord/discord.go, pkg/handler/discord/interface.go, pkg/routes/v1.go, pkg/routes/v1_test.go, pkg/service/discord/const.go, pkg/service/discord/discord.go, pkg/service/discord/service.go, pkg/store/memolog/memo_log.go
=> feat: add cronjob to notify weekly memos to discord channel

migrations/schemas/20240513093025-extend_table_discount_accounts.sql
fix: migrate failed because of null value
=> fix: migrate failed because of null value

Makefile, README.md, devbox.json, devbox.lock
https://github.com/dwarvesf/fortress-api/assets/32956772/7946be63-c170-46d1-9c2f-b0e4bd357943
=> chore: setup devbox

pkg/config/config.go, pkg/handler/discord/discord.go, pkg/routes/v1.go, pkg/service/service.go, pkg/service/youtube/interface.go, pkg/service/youtube/youtube.go
=> feat: add svc youtube to broadcast ogif

pkg/handler/discord/discord.go, pkg/handler/discord/request/request.go, pkg/model/event.go, pkg/service/youtube/youtube.go
=> chore: add cover img to yt broadcast

pkg/handler/youtube/interface.go, pkg/handler/youtube/youtube.go, pkg/routes/v1.go, pkg/routes/v1_test.go
=> feat: add api to get latest yt broadcast

migrations/schemas/20241030151941-view-project-cost-and-revenue.sql, pkg/controller/employee/update_employee_status.go, pkg/model/employees.go, pkg/service/googlemail/google_mail.go, pkg/service/googlemail/interface.go, pkg/templates/offboarding_keep_fwd_email.tpl
=> feat: add template email for offboarding that keeps forwarded emails

migrations/schemas/20250122042534-alter_table_projects_add_project_artifact_link.sql, pkg/model/projects.go
=> feat: add column 'artifact_link' to projects table
